# cmux non-NixOS distro package tests.
# Uses nix-vm-test (numtide) to boot real distro QEMU VMs and verify
# that .deb and .rpm release packages install, resolve deps, and run.
#
# Tests use pre-built release artifacts downloaded from GitHub, not
# Nix-built packages. This tests what users actually install.
#
# Available checks:
#   nix build .#checks.x86_64-linux.distro-fedora42
#   nix build .#checks.x86_64-linux.distro-rocky9
#   nix build .#checks.x86_64-linux.distro-rocky10
#   nix build .#checks.x86_64-linux.distro-debian12
#   nix build .#checks.x86_64-linux.distro-ubuntu2404
#
# Note: `distro-rocky9` is currently a legacy RPM-install proxy. The actual
# constrained RHEL-family target is Rocky 10. A real `distro-rocky10` check is
# only exported when the manifest defines a distinct `rpmRocky` asset.
#
# Requires KVM for acceptable performance (/dev/kvm).
# Runs on honey self-hosted runner via test-distro.yml.
{
  self,
  system,
  nixpkgs,
  nix-vm-test,
  ...
}: let
  lib = nixpkgs.lib;

  pkgs = import nixpkgs {
    inherit system;
  };

  nvt = nix-vm-test.lib.${system};
  nvtGeneric = pkgs.callPackage "${nix-vm-test.outPath}/generic" {
    inherit nixpkgs;
  };

  # ── Fetch release artifacts from GitHub ──────────────────────────
  # Default to the checked-in release manifest. A local override manifest can be
  # generated by workflow/manual tooling when validating a specific release tag.
  releaseArtifacts =
    import
    (if builtins.pathExists ./release-artifacts.override.nix
    then ./release-artifacts.override.nix
    else ./release-artifacts.nix);
  releaseTag = releaseArtifacts.releaseTag or null;
  releaseBase =
    if releaseTag == null
    then null
    else "https://github.com/Jesssullivan/cmux/releases/download/${releaseTag}";

  materializeReleaseAsset = asset:
    if asset ? path
    then
      builtins.path (
        {
          path = asset.path;
        }
        // lib.optionalAttrs (asset ? name) {name = asset.name;}
      )
    else
      pkgs.fetchurl {
        url = "${releaseBase}/${asset.name}";
        hash = asset.hash;
      };

  materializeReleaseAssetDir = label: asset: let
    artifact = materializeReleaseAsset asset;
    name =
      if asset ? name
      then asset.name
      else builtins.baseNameOf (toString artifact);
  in
    pkgs.runCommand "${label}-artifact-dir" {} ''
      mkdir -p "$out"
      cp ${artifact} "$out/${name}"
    '';

  releaseAssetName = asset:
    if asset ? name
    then asset.name
    else builtins.baseNameOf (toString (materializeReleaseAsset asset));

  injectReleaseAssetIntoImage = label: image: asset: let
    artifact = materializeReleaseAsset asset;
    name = releaseAssetName asset;
  in
    pkgs.runCommand "${label}-image-with-asset" {} ''
      install -m 0600 ${image} image.qcow2
      mkdir -p pkg
      cp ${artifact} "pkg/${name}"
      chmod 0644 "pkg/${name}"
      ${pkgs.guestfs-tools}/bin/virt-customize \
        -a image.qcow2 \
        --smp 2 \
        --memsize 256 \
        --no-network \
        --copy-in "pkg/${name}:/opt"
      cp image.qcow2 "$out"
    '';

  # RHEL-family cloud images used by nix-vm-test do not expose 9p in the
  # guest kernel, so sharedDirs cannot carry package artifacts into Rocky.
  makeRockyPackageTest = imageId: rpmAsset: testScript: let
    baseImage = nvt.rocky.prepareRockyImage {
      hostPkgs = pkgs;
      originalImage = nvt.rocky.images.${imageId};
      diskSize = null;
      extraPathsToRegister = [];
    };
    image = injectReleaseAssetIntoImage "rocky-${imageId}-cmux-package" baseImage rpmAsset;
  in
    (nvtGeneric.makeVmTest {
      name = "vm-test-rocky_${imageId}_cmux";
      inherit system image testScript;
      sharedDirs = {};
    }).sandboxed;

  cmuxDebDir = materializeReleaseAssetDir "cmux-deb" releaseArtifacts.assets.deb;

  cmuxFedoraRpmDir = materializeReleaseAssetDir "cmux-fedora-rpm" (releaseArtifacts.assets.rpmFedora or releaseArtifacts.assets.rpm);
  haveRockyRpm = releaseArtifacts.assets ? rpmRocky;
  cmuxRockyRpmDir =
    if haveRockyRpm
    then materializeReleaseAssetDir "cmux-rocky-rpm" releaseArtifacts.assets.rpmRocky
    else cmuxFedoraRpmDir;

  # ── Shared socket ping test snippet ──────────────────────────────
  # Used by all distro tests after package install.
  socketPingTest = ''
    # Verify binary runs
    vm.succeed("cmux --version 2>&1 || cmux --help 2>&1 || echo 'binary runs'")

    # Verify runtime library deps resolve cleanly after package install
    vm.succeed("""
      ldd_out="$(ldd /usr/bin/cmux 2>&1)"
      echo "$ldd_out" | head -20
      ! echo "$ldd_out" | grep -q "not found"
    """)
  '';

  rockyNetworkBootstrap = ''
    # Rocky images can boot under QEMU user networking without a populated
    # resolver config. 10.0.2.3 is QEMU's built-in DNS endpoint.
    vm.succeed("printf 'nameserver 10.0.2.3\\noptions timeout:1 attempts:3\\n' > /etc/resolv.conf")
    vm.succeed("ip route show && cat /etc/resolv.conf")
  '';

  distro-fedora42 =
    (nvt.fedora."42" {
      sharedDirs = {
        pkg = {
          source = "${cmuxFedoraRpmDir}";
          target = "/mnt/pkg";
        };
      };
      testScript = ''
        vm.wait_for_unit("multi-user.target")

        vm.succeed("timeout 300 dnf makecache")
        vm.succeed("timeout 300 dnf install -y /mnt/pkg/*")

        # Verify binary is installed
        vm.succeed("test -f /usr/bin/cmux")

        ${socketPingTest}
      '';
    }).sandboxed;

  distro-rocky10 =
    makeRockyPackageTest "10_1" (releaseArtifacts.assets.rpmRocky or releaseArtifacts.assets.rpm) ''
        vm.wait_for_unit("multi-user.target")

        ${rockyNetworkBootstrap}

        vm.succeed("timeout 300 dnf install -y dnf-plugins-core")
        vm.succeed("dnf config-manager --set-enabled crb")
        vm.succeed("timeout 300 dnf makecache")

        # Install the constrained Rocky 10 RPM
        vm.succeed("timeout 300 dnf install -y /opt/*.rpm")

        # Verify binary is installed
        vm.succeed("test -f /usr/bin/cmux")

        ${socketPingTest}
      '';

  # ── Test: Rocky Linux 9 RPM install proxy ────────────────────────
  distro-rocky9 =
    makeRockyPackageTest "9_5" (releaseArtifacts.assets.rpmFedora or releaseArtifacts.assets.rpm) ''
        vm.wait_for_unit("multi-user.target")

        ${rockyNetworkBootstrap}

        # Enable EPEL for GTK4/libadwaita on Rocky 9
        vm.succeed("timeout 300 dnf install -y epel-release")
        vm.succeed("timeout 300 dnf makecache")

        # Install the RPM
        vm.succeed("rpm -ivh /opt/*.rpm || timeout 300 dnf install -y /opt/*.rpm")

        # Verify binary is installed
        vm.succeed("test -f /usr/bin/cmux")

        ${socketPingTest}
      '';

  # ── Test: Debian 12 DEB install ──────────────────────────────────
  distro-debian12 =
    (nvt.debian."12" {
      sharedDirs = {
        pkg = {
          source = "${cmuxDebDir}";
          target = "/mnt/pkg";
        };
      };
      testScript = ''
        vm.wait_for_unit("multi-user.target")

        vm.succeed("timeout 300 apt-get update")

        # Install the DEB and resolve dependencies
        vm.succeed("dpkg -i /mnt/pkg/* || timeout 300 apt-get install -f -y")

        # Verify binary is installed
        vm.succeed("test -f /usr/bin/cmux")

        ${socketPingTest}
      '';
    }).sandboxed;

  # ── Test: Ubuntu 24.04 DEB install ───────────────────────────────
  distro-ubuntu2404 =
    (nvt.ubuntu."24_04" {
      sharedDirs = {
        pkg = {
          source = "${cmuxDebDir}";
          target = "/mnt/pkg";
        };
      };
      testScript = ''
        vm.wait_for_unit("multi-user.target")

        vm.succeed("timeout 300 apt-get update")

        # Install the DEB and resolve dependencies
        vm.succeed("dpkg -i /mnt/pkg/* || timeout 300 apt-get install -f -y")

        # Verify binary is installed
        vm.succeed("test -f /usr/bin/cmux")

        ${socketPingTest}
      '';
    }).sandboxed;

  checks = {
    inherit distro-fedora42 distro-rocky9 distro-debian12 distro-ubuntu2404;
  } // lib.optionalAttrs haveRockyRpm {
    inherit distro-rocky10;
  };
in
  checks
