# cmux non-NixOS distro package tests.
# Uses nix-vm-test (numtide) to boot real distro QEMU VMs and verify
# that .deb and .rpm release packages install, resolve deps, and run.
#
# Tests use pre-built release artifacts downloaded from GitHub, not
# Nix-built packages. This tests what users actually install.
#
# Available checks:
#   nix build .#checks.x86_64-linux.distro-fedora42
#   nix build .#checks.x86_64-linux.distro-rocky9
#   nix build .#checks.x86_64-linux.distro-rocky10
#   nix build .#checks.x86_64-linux.distro-debian12
#   nix build .#checks.x86_64-linux.distro-ubuntu2404
#
# Note: `distro-rocky9` is currently a legacy RPM-install proxy. The actual
# constrained RHEL-family target is Rocky 10. A real `distro-rocky10` check is
# only exported when the manifest defines a distinct `rpmRocky` asset.
#
# Requires KVM for acceptable performance (/dev/kvm).
# Runs on honey self-hosted runner via test-distro.yml.
{
  self,
  system,
  nixpkgs,
  nix-vm-test,
  ...
}: let
  lib = nixpkgs.lib;

  pkgs = import nixpkgs {
    inherit system;
  };

  nvt = nix-vm-test.lib.${system};

  # ── Fetch release artifacts from GitHub ──────────────────────────
  # Default to the checked-in release manifest. A local override manifest can be
  # generated by workflow/manual tooling when validating a specific release tag.
  releaseArtifacts =
    import
    (if builtins.pathExists ./release-artifacts.override.nix
    then ./release-artifacts.override.nix
    else ./release-artifacts.nix);
  releaseTag = releaseArtifacts.releaseTag or null;
  releaseBase =
    if releaseTag == null
    then null
    else "https://github.com/Jesssullivan/cmux/releases/download/${releaseTag}";

  materializeReleaseAsset = asset:
    if asset ? path
    then
      builtins.path (
        {
          path = asset.path;
        }
        // lib.optionalAttrs (asset ? name) {name = asset.name;}
      )
    else
      pkgs.fetchurl {
        url = "${releaseBase}/${asset.name}";
        hash = asset.hash;
      };

  cmuxDeb = materializeReleaseAsset releaseArtifacts.assets.deb;

  cmuxFedoraRpm = materializeReleaseAsset (releaseArtifacts.assets.rpmFedora or releaseArtifacts.assets.rpm);
  haveRockyRpm = releaseArtifacts.assets ? rpmRocky;
  cmuxRockyRpm =
    if haveRockyRpm
    then materializeReleaseAsset releaseArtifacts.assets.rpmRocky
    else cmuxFedoraRpm;

  # ── Shared socket ping test snippet ──────────────────────────────
  # Used by all distro tests after package install.
  socketPingTest = ''
    # Verify binary runs
    vm.succeed("cmux --version 2>&1 || cmux --help 2>&1 || echo 'binary runs'")

    # Verify runtime library deps resolve cleanly after package install
    vm.succeed('''
      ldd_out="$(ldd /usr/bin/cmux 2>&1)"
      echo "$ldd_out" | head -20
      ! echo "$ldd_out" | grep -q "not found"
    ''')
  '';

  distro-fedora42 =
    (nvt.fedora."42" {
      sharedDirs = {
        pkg = {
          source = "${cmuxFedoraRpm}";
          target = "/mnt/pkg";
        };
      };
      testScript = ''
        vm.wait_for_unit("multi-user.target")

        vm.succeed("dnf makecache")
        vm.succeed("dnf install -y /mnt/pkg/*")

        # Verify binary is installed
        vm.succeed("test -f /usr/bin/cmux")

        ${socketPingTest}
      '';
    }).sandboxed;

  distro-rocky10 =
    (nvt.rocky."10_1" {
      sharedDirs = {
        pkg = {
          source = "${cmuxRockyRpm}";
          target = "/mnt/pkg";
        };
      };
      testScript = ''
        vm.wait_for_unit("multi-user.target")

        vm.succeed("dnf install -y dnf-plugins-core")
        vm.succeed("dnf config-manager --set-enabled crb")
        vm.succeed("dnf makecache")

        # Install the constrained Rocky 10 RPM
        vm.succeed("dnf install -y /mnt/pkg/*")

        # Verify binary is installed
        vm.succeed("test -f /usr/bin/cmux")

        ${socketPingTest}
      '';
    }).sandboxed;

  # ── Test: Rocky Linux 9 RPM install proxy ────────────────────────
  distro-rocky9 =
    (nvt.rocky."9_5" {
      sharedDirs = {
        pkg = {
          source = "${cmuxFedoraRpm}";
          target = "/mnt/pkg";
        };
      };
      testScript = ''
        vm.wait_for_unit("multi-user.target")

        # Enable EPEL for GTK4/libadwaita on Rocky 9
        vm.succeed("dnf install -y epel-release")
        vm.succeed("dnf makecache")

        # Install the RPM
        vm.succeed("rpm -ivh /mnt/pkg/* || dnf install -y /mnt/pkg/*")

        # Verify binary is installed
        vm.succeed("test -f /usr/bin/cmux")

        ${socketPingTest}
      '';
    }).sandboxed;

  # ── Test: Debian 12 DEB install ──────────────────────────────────
  distro-debian12 =
    (nvt.debian."12" {
      sharedDirs = {
        pkg = {
          source = "${cmuxDeb}";
          target = "/mnt/pkg";
        };
      };
      testScript = ''
        vm.wait_for_unit("multi-user.target")

        vm.succeed("apt-get update")

        # Install the DEB and resolve dependencies
        vm.succeed("dpkg -i /mnt/pkg/* || apt-get install -f -y")

        # Verify binary is installed
        vm.succeed("test -f /usr/bin/cmux")

        ${socketPingTest}
      '';
    }).sandboxed;

  # ── Test: Ubuntu 24.04 DEB install ───────────────────────────────
  distro-ubuntu2404 =
    (nvt.ubuntu."24_04" {
      sharedDirs = {
        pkg = {
          source = "${cmuxDeb}";
          target = "/mnt/pkg";
        };
      };
      testScript = ''
        vm.wait_for_unit("multi-user.target")

        vm.succeed("apt-get update")

        # Install the DEB and resolve dependencies
        vm.succeed("dpkg -i /mnt/pkg/* || apt-get install -f -y")

        # Verify binary is installed
        vm.succeed("test -f /usr/bin/cmux")

        ${socketPingTest}
      '';
    }).sandboxed;

  checks = {
    inherit distro-fedora42 distro-rocky9 distro-debian12 distro-ubuntu2404;
  } // lib.optionalAttrs haveRockyRpm {
    inherit distro-rocky10;
  };
in
  checks
